name: Java CI with Gradle

on:
  push:
    branches: ["none_for_now_because_we_can't_afford_to_pay_for_it"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: ["none_for_now_because_we_can't_afford_to_pay_for_it"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    permissions:
      contents: read
      actions: read
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build desktop:dist jacocoTestReport

    - name: Upload game JAR
      uses: actions/upload-artifact@v4
      with:
          name: HesHustle-${{ matrix.os }}.jar
          path: desktop/build/libs/desktop-1.0.jar

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-${{ matrix.os }}
        path: tests/build/reports/jacoco/test/html/
    
    - name: Add Test Report to GitHub
      uses: dorny/test-reporter@v1
      if: always() # Run even if previous steps failed
      with:
        name: "Test Report ${{ matrix.os }}"
        path: tests/build/test-results/test/**.xml
        reporter: java-junit
        fail-on-error: 'true'
        fail-on-empty: 'true'

    - name: Upload core checkstyle report
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'macos')
      with:
        name: checkstyle-report-core
        path: core/build/reports/checkstyle

    - name: Upload tests checkstyle report
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'macos')
      with:
        name: checkstyle-report-tests
        path: tests/build/reports/checkstyle

  dependency-submission:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3

  release:
    runs-on: macos-latest
    needs: ["build"]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
        contents: write

    steps:
    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: HesHustle-windows-latest.jar
    - name: Rename Windows build artifact
      run: mv desktop-1.0.jar HesHustle-windows.jar

    - name: Download MacOS build artifact
      uses: actions/download-artifact@v4
      with:
        name: HesHustle-macos-latest.jar
    - name: Rename MacOS build artifact
      run: mv desktop-1.0.jar HesHustle-macos.jar

    - name: Download Ubuntu build artifact
      uses: actions/download-artifact@v4
      with:
        name: HesHustle-ubuntu-latest.jar
    - name: Rename Ubuntu build artifact
      run: mv desktop-1.0.jar HesHustle-ubuntu.jar

    - name: Release
      uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
      with:
        files: HesHustle*.jar
