name: Java CI with Gradle

on:
  push:
    branches: ["ci"]
  pull_request:
    branches: ["ci"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload game JAR
      uses: actions/upload-artifact@v4
      with:
          name: HesHustle.jar
          path: desktop/build/libs/lib.jar
    - name: Upload game JAR 2
      uses: actions/upload-artifact@v4
      with:
        name: HesHustle2.jar
        path: desktop/build/libs/Heslington Hustle.jar
    - name: Upload game JAR 3
      uses: actions/upload-artifact@v4
      with:
        name: HesHustle3.jar
        path: desktop/build/libs/HustleGame.jar
    - name: Upload game JAR 4
      uses: actions/upload-artifact@v4
      with:
        name: HesHustle4.jar
        path: desktop/build/libs/skloch.jar
    - name: Upload game JAR 5
      uses: actions/upload-artifact@v4
      with:
        name: HesHustle5.jar
        path: desktop/build/libs/game.jar
    - name: Upload game JAR 6
      uses: actions/upload-artifact@v4
      with:
        name: HesHustle6.jar
        path: desktop/build/libs/HesHustle.jar