name: Java CI with Gradle

on:
  push:
    branches: ["ci"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  pull_request:
    branches: ["ci"]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload game JAR
      uses: actions/upload-artifact@v4
      with:
          name: HesHustle-${{ matrix.os }}.jar
          path: desktop/build/libs/desktop-1.0.jar

    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report-${{ matrix.os }}
        path: core/build/reports/jacoco/test/html/

    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      if: startsWith(matrix.os, 'windows')
      with:
        name: checkstyle-report
        path: core/build/reports/checkstyle

  release:
    runs-on: ubuntu-latest
    needs: ["build"]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
        contents: write

    steps:
    - name: Download Windows build artifact
      uses: actions/download-artifact@v4
      with:
        name: HesHustle-windows-latest.jar

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: HesHustle*.jar